//burder
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE'
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS'
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS'

//modal
export const ORDER_NOW_OPEN = 'ORDER_NOW_OPEN'
export const ORDER_NOW_CLOSE = 'ORDER_NOW_CLOSE'

//order
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'
export const PURCHASE_INIT = 'PURCHASE_INIT'
export const PURCHASE_BURGER_BEFORE_START = 'PURCHASE_BURGER_BEFORE_START'
export const FETCH_ORDERS_BEFORE_START = 'FETCH_ORDERS_BEFORE_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'

//auth
export const INIT_AUTH = 'INIT_AUTH'
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_INIT_LOGOUT = 'AUTH_INIT_LOGOUT'
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_FOR_ORDER = 'AUTH_FOR_ORDER'
