export const ADD_INGREDIENTS = 'ADD_INGREDIENTS'
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS'

export const ORDER_NOW_OPEN = 'ORDER_NOW_OPEN'
export const ORDER_NOW_CLOSE = 'ORDER_NOW_CLOSE'

export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'
